# Generated by Django 5.2.8 on 2026-02-20 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(choices=[('gyms_directory', 'Gyms Directory'), ('clients_overview', 'Clients Overview'), ('subscription_payments', 'Subscription Payments')], max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('template_file', models.FileField(upload_to='print_templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['report_key', 'is_active'], name='gymReports__report__ae12ca_idx')],
            },
        ),
    ]
