from .address import AddressForm
from .bug_report import BugReportForm
from .equipment import EquipmentForm
from .exercise import ExerciseForm
from .exercise_type import ExerciseTypeForm
from .gym import GymForm
from .login import LoginForm
from .new_feature_request import NewFeatureRequestForm
from .staff import StaffForm
from .subscription import SubscriptionPlanForm
from .subscription_payment import SubscriptionPaymentForm
from .update_staff import UpdateStaffForm
from .workout_day import WorkoutDayForm
from .workout_item import WorkoutItemForm
from .workout_plan import WorkoutPlanForm
